import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1>hiii</h1>
    </div>
  )
}

// export async function getServerSideProps() {

//   const response= await fetch('http://localhost:1337/api/products', {
//     method: 'GET',
//     headers: {
//       authorization: 'Bearer bda31179510b8b83233ce336d126178a1c5c7766ec53e317058fa9f82991fd65e0f00962ef9da14c46fe38a4c39530f16c0cb1cb8e0f8a95659c35b47f7cc4e4668b3cd26d6c56fd072a872f24c4a2a83e98d77426c20ae25aecb43b63af66e25d2f9c9544f545ab9de35b1661a161691b2acdc36b1350d7e824586dcd48364f'
//     },
//   });
//   const data = await response.json()
//   console.log(data.data,"data");
//   return {
//     props: {
//       data:[]
//     }, // will be passed to the page component as props
//   }
// }
